# Generated by Django 5.1.2 on 2024-11-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='old'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(default=' '),
        ),
    ]
